branch-defaults:
  master:
    environment: sale-chaintrade-staging
global:
  application_name: sale-chaintrade
  default_ec2_keyname: sale-chaintrade
  default_platform: 64bit Amazon Linux 2017.09 v4.4.0 running Node.js
  default_region: ap-southeast-1
  profile: eb-cli
  sc: git